package com.birdshel.Uciana.Resources;

/* compiled from: MyApplication */
/* loaded from: classes.dex */
public enum ButtonsEnum {
    MENU,
    SYSTEM,
    TURN,
    SCIENCE,
    CREDITS,
    RACES,
    BIRDSHEL,
    GALAXY,
    PRODUCTION_WARN,
    BLANK_BLUE,
    PREVIOUS,
    NEXT,
    COLONIES,
    CLOSE,
    PRODUCTION,
    HISTORY,
    BUILDINGS,
    SETTINGS,
    EMPIRE,
    _NOT_USED_1,
    _NOT_USED_2,
    _NOT_USED_3,
    _NOT_USED_4,
    _NOT_USED_5,
    RADIO_ON,
    RADIO_OFF,
    BUY_PRODUCTION,
    PRESSED,
    SHIP_SELECT,
    FLEETS,
    BLANK,
    CREDITS_WARN,
    PLANET,
    SHIP_YARD,
    EVENTS,
    OK,
    TECH_WARN,
    ZOOM,
    AUTO_ATTACK,
    ATTACK,
    BOMBARD,
    WEAPON,
    INVADE,
    AUTO_BUILD
}
